#!/bin/sh
# see: dh_installdeb(1)

set -e

# source debconf library
. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /usr/share/dbconfig-common/dpkg/postinst.pgsql  ]; then
  . /usr/share/dbconfig-common/dpkg/postinst.pgsql
fi

unset_links () {
    if [ ! "upgrade" = "$1" ]; then
        rm -f /usr/bin/pi-appliance
	rm -f /usr/bin/pi-appliance-update
    fi
}

unset_links $1

#DEBHELPER#
exit 0
